import { AppError } from "@/lib/errors";
import type { ActionArea, ActionPatch, AssetScope, CollaboratorPatch, CreateActionInput, CreateCollaboratorInput, CreateProjectInput, ProjectTransitionInput, TransitionInput } from "@/lib/types";

const AREAS: ActionArea[] = ["project", "personal", "knowledge", "candidate"];
const SCOPES: AssetScope[] = ["personal", "organization", "project", "brand"];
const TRANSITIONS: TransitionInput["transition"][] = ["start", "wait", "schedule", "carryover", "complete", "cancel"];
const PROJECT_TRANSITIONS: ProjectTransitionInput["transition"][] = ["archive", "restore"];

function invalid(message: string): never { throw new AppError(message, 422, "INVALID_INPUT"); }
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) invalid("请求体必须是 JSON 对象。"); return value as Record<string, unknown>; }
function required(input: Record<string, unknown>, key: string, label: string): string { const value = input[key]; if (typeof value !== "string" || !value.trim()) invalid(`请填写${label}。`); return value; }
function optionalString(input: Record<string, unknown>, key: string): string | undefined { const value = input[key]; if (value === undefined) return undefined; if (typeof value !== "string") invalid(`${key} 必须是文本。`); return value; }
function strings(input: Record<string, unknown>, key: string): string[] | undefined { const value = input[key]; if (value === undefined) return undefined; if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) invalid(`${key} 必须是文本数组。`); return value; }
function enumValue<T extends string>(value: unknown, allowed: readonly T[], field: string): T { if (typeof value !== "string" || !allowed.includes(value as T)) invalid(`${field}无效。`); return value as T; }

export async function jsonObject(request: Request): Promise<Record<string, unknown>> { try { return record(await request.json()); } catch (error) { if (error instanceof AppError) throw error; throw new AppError("请求体不是合法 JSON。", 400, "INVALID_JSON"); } }
export async function parseCreateAction(request: Request): Promise<CreateActionInput> { const input = await jsonObject(request); return { title: required(input, "title", "事项名称"), actionArea: enumValue(input.actionArea, AREAS, "任务范围"), project: optionalString(input, "project"), workstreams: strings(input, "workstreams"), nextAction: required(input, "nextAction", "下一动作"), completionStandard: required(input, "completionStandard", "完成标准"), startOn: optionalString(input, "startOn"), dueOn: optionalString(input, "dueOn"), scheduledFor: optionalString(input, "scheduledFor"), assetScope: input.assetScope === undefined ? undefined : enumValue(input.assetScope, SCOPES, "资产范围") }; }
export async function parseCreateProject(request: Request): Promise<CreateProjectInput> { const input = await jsonObject(request); return { name: required(input, "name", "项目名称"), goal: required(input, "goal", "项目目标"), successCriteria: required(input, "successCriteria", "成功标准"), nextAction: required(input, "nextAction", "下一步行动"), targetDate: optionalString(input, "targetDate") }; }
export async function parseCreateCollaborator(request: Request): Promise<CreateCollaboratorInput> { const input = await jsonObject(request); return { name: required(input, "name", "协作人姓名"), aliases: strings(input, "aliases"), relationshipRoles: strings(input, "relationshipRoles") ?? invalid("请填写协作角色。"), projects: strings(input, "projects"), collaborationTopics: strings(input, "collaborationTopics"), sourceNotes: strings(input, "sourceNotes"), sourceThreads: strings(input, "sourceThreads") }; }
export async function parseCollaboratorPatch(request: Request): Promise<CollaboratorPatch> { const input = await jsonObject(request); const patch: CollaboratorPatch = { expectedVersion: required(input, "expectedVersion", "版本号") }; for (const key of ["aliases", "relationshipRoles", "projects", "collaborationTopics", "sourceNotes", "sourceThreads"] as const) { const value = strings(input, key); if (value !== undefined) patch[key] = value; } return patch; }
export async function parseActionPatch(request: Request): Promise<ActionPatch> { const input = await jsonObject(request); const patch: ActionPatch = { expectedVersion: required(input, "expectedVersion", "版本号") }; if (input.actionArea !== undefined) patch.actionArea = enumValue(input.actionArea, AREAS, "任务范围"); if (input.assetScope !== undefined) patch.assetScope = enumValue(input.assetScope, SCOPES, "资产范围"); for (const key of ["nextAction", "completionStandard", "startOn", "dueOn", "scheduledFor", "reviewOn"] as const) { const value = optionalString(input, key); if (value !== undefined) patch[key] = value; } patch.projects = strings(input, "projects"); patch.workstreams = strings(input, "workstreams"); return patch; }
export async function parseTransition(request: Request): Promise<TransitionInput> { const input = await jsonObject(request); return { expectedVersion: required(input, "expectedVersion", "版本号"), transition: enumValue(input.transition, TRANSITIONS, "状态操作"), note: optionalString(input, "note"), reviewOn: optionalString(input, "reviewOn"), scheduledFor: optionalString(input, "scheduledFor") }; }
export async function parseProjectTransition(request: Request): Promise<ProjectTransitionInput> { const input = await jsonObject(request); return { expectedVersion: required(input, "expectedVersion", "版本号"), transition: enumValue(input.transition, PROJECT_TRANSITIONS, "项目状态操作") }; }
